### ISSUE TITLE
500 Error

### ISSUE THREAD

**Issue by tharveyster** [myogeshchavan97/contact-us-form#3]
Using the code as is, and a valid gmail account with allow less secure apps enabled, I get a 500 error on message submission.

**Comment by myogeshchavan97** [comment]
@tharveyster Please add a console.log inside the if condition to see the error [here](https://github.com/myogeshchavan97/contact-us-form/blob/master/server/index.js#L31) like this:

```js
if (err) {
   console.log(err);
   ...
}
```

This will help you to identify the exact error you're getting from the server.

Also, make sure to restart the app after adding the console.log

**Comment by tharveyster** [comment]
I figured it out. I had to addtls: {  rejectUnauthorized: false}to the transporter.Sent from my Galaxy
-------- Original message --------From: Yogesh Chavan ***@***.***> Date: 2/8/22  4:43 AM  (GMT-05:00) To: myogeshchavan97/contact-us-form ***@***.***> Cc: Todd Harvey ***@***.***>, Mention ***@***.***> Subject: Re: [myogeshchavan97/contact-us-form] 500 Error (Issue #3) 
@tharveyster Please add a console.log inside the if condition to see the error here.
This will help you to identify the exact error you're getting from the server.
Also, make sure to restart the app after adding the console.log

—Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android.
You are receiving this because you were mentioned.Message ID: ***@***.***>
[
{
***@***.***": "http://schema.org",
***@***.***": "EmailMessage",
"potentialAction": {
***@***.***": "ViewAction",
"target": "https://github.com/myogeshchavan97/contact-us-form/issues/3#issuecomment-1032406844",
"url": "https://github.com/myogeshchavan97/contact-us-form/issues/3#issuecomment-1032406844",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
***@***.***": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by myogeshchavan97** [comment]
Awesome
